mysite/accounts/urls.py
from django.urls import path, reverse_lazy, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name ='accounts'

urlpatterns = [
    path('', views.homeView, name='home'),
    path('register/', views.register, name='register'),  # Added trailing slash for consistency
    path('login/', views.login_view, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),  # Added trailing slash for consistency
    path('profile/', views.profile, name='profile'),
    path("password_change", views.password_change, name="password_change"),
    path("password_reset", views.password_reset_request, name="password_reset"),
    path('reset/<uidb64>/<token>', views.passwordResetConfirm, name='password_reset_confirm'),    
    ]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('products/', include('products.urls')),
]

mysite/products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.ProductList.as_view(), name='product-list'),
    path('products/<int:pk>/', views.ProductDetail.as_view(), name='product-detail'),
    path('categories/', views.CategoryList.as_view(), name='category-list'),
    path('categories/<int:pk>/', views.CategoryDetail.as_view(), name='category-detail'),
]

mysite/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
from phonenumber_field.modelfields import PhoneNumberField


# Create your models here.
class CustomUser(AbstractUser):
    email = models.EmailField(unique=True)
    address = models.CharField("Address", max_length=300, default='', blank=True)
    phone_number = PhoneNumberField(null=True, blank=True)
    image = models.ImageField(upload_to='images/', blank=True, null=True)
    
    # Add related_name to groups and user_permissions fields
    groups = models.ManyToManyField(
        'auth.Group',
        related_name='custom_users',  # Choose a custom related_name
        blank=True,
        help_text='The groups this user belongs to.',
        verbose_name='groups',
    )

    user_permissions = models.ManyToManyField(
        'auth.Permission',
        related_name='custom_users',  # Choose a custom related_name
        blank=True,
        help_text='Specific permissions for this user.',
        verbose_name='user permissions',
    )

    def __str__(self):
        return self.username

mysite/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, SetPasswordForm, PasswordResetForm
from django.contrib.auth import get_user_model
from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV2Checkbox 
from .models import CustomUser


class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(help_text='A valid email address, please.', required=True)

    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']

    def save(self, commit=True):
        user = super(UserRegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()

        return user
    
class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Username or Email'}),
        label="Username or Email*")

    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Password'}))
    
    captcha = ReCaptchaField(widget=ReCaptchaV2Checkbox())
    
class UserUpdateForm(forms.ModelForm):
    model = CustomUser
    email = forms.EmailField()

    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email', 'phone_number', 'address', 'image']


class SetPasswordForm(SetPasswordForm):
    class Meta:
        model = get_user_model()
        fields = ['new_password1', 'new_password2']

class PasswordResetForm(PasswordResetForm):
    def __init__(self, *args, **kwargs):
        super(PasswordResetForm, self).__init__(*args, **kwargs)

    captcha = ReCaptchaField(widget=ReCaptchaV2Checkbox())
    

mysite/accounts/views.py
from django.shortcuts import render, redirect
from .models import CustomUser
from django.contrib.auth import get_user_model, login, authenticate, logout
from .forms import UserRegistrationForm,UserLoginForm, UserUpdateForm, SetPasswordForm, PasswordResetForm
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.db import transaction
from django.contrib.auth.decorators import login_required
from .decorators import user_not_authenticated
from .tokens import account_activation_token
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.core.mail import EmailMessage
from django.db.models.query_utils import Q
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404, redirect
from django.views.decorators.http import require_POST
from django.contrib import messages
from products.models import Product


# Create your views here.
from django.contrib.auth.decorators import login_required


def homeView(request):
    products = Product.objects.all()
    if request.user.is_authenticated:
        user = request.user
        context = {'user': user, 'products': products}
    else:
        context = {}
    return render(request, 'accounts/home.html', context)


def activate(request, uidb64, token):
    User = get_user_model()
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except:
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()

        messages.success(request, "Thank you for your email confirmation. Now you can login your account.")
        return redirect('accounts:login')
    else:
        messages.error(request, "Activation link is invalid!")

    return redirect('accounts:login')

def activateEmail(request, user, to_email):
    mail_subject = "Activate your user account."
    message = render_to_string("accounts/template_activate_account.html", {
        'user': user.username,
        'domain': get_current_site(request).domain,
        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
        'token': account_activation_token.make_token(user),
        "protocol": 'https' if request.is_secure() else 'http'
    })
    email = EmailMessage(mail_subject, message, to=[to_email])
    if email.send():
        messages.success(request, f'Dear <b>{user}</b>, please go to you email <b>{to_email}</b> inbox and click on \
                received activation link to confirm and complete the registration. <b>Note:</b> Check your spam folder.')
    else:
        messages.error(request, f'Problem sending email to {to_email}, check if you typed it correctly.')

@user_not_authenticated
def register(request):
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active=False
            user.save()
            activateEmail(request, user, form.cleaned_data.get('email'))
            return redirect('accounts:login')
        else:
            for error in list(form.errors.values()):
                messages.error(request, error)
    else:
        form = UserRegistrationForm()

    return render(
        request=request,
        template_name="accounts/register.html",
        context={"form": form}
    )
    
@user_not_authenticated
def login_view(request):
    if request.method == "POST":
        form = UserLoginForm(request=request, data=request.POST)
        if form.is_valid():
            user = authenticate(
                username=form.cleaned_data["username"],
                password=form.cleaned_data["password"],
            )
            if user is not None:
                login(request, user)
                messages.success(request, f"Hello <b>{user.username}</b>! You have been logged in")
                return redirect("accounts:home")

        else:
            for key, error in list(form.errors.items()):
                if key == 'captcha' and error[0] == 'This field is required.':
                    messages.error(request, "You must pass the reCAPTCHA test")
                    continue
                
                messages.error(request, error) 
 

    form = UserLoginForm()

    return render(
        request=request,
        template_name="accounts/login.html",
        context={"form": form}
        )

from django.contrib.auth.decorators import login_required

@login_required
def profile(request):
    if request.method == "POST":
        user = request.user
        form = UserUpdateForm(request.POST, request.FILES, instance=user)

        if form.is_valid():
            form.save()
            messages.success(request, f'Your profile has been updated!')
            return redirect("accounts:profile")

        for error in list(form.errors.values()):
            messages.error(request, error)
    
    form = UserUpdateForm(instance=request.user)
    return render(
        request=request,
        template_name="accounts/profile.html",
        context={"form": form}
    )


@login_required
def password_change(request):
    user = request.user
    if request.method == 'POST':
        form = SetPasswordForm(user, request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Your password has been changed")
            return redirect('accounts:login')
        else:
            for error in list(form.errors.values()):
                messages.error(request, error)

    form = SetPasswordForm(user)
    return render(request, 'accounts/password_reset_confirm.html', {'form': form})

@user_not_authenticated
def password_reset_request(request):
    if request.method == 'POST':
        form = PasswordResetForm(request.POST)
        if form.is_valid():
            user_email = form.cleaned_data['email']
            associated_user = get_user_model().objects.filter(Q(email=user_email)).first()
            if associated_user:
                subject = "Password Reset request"
                message = render_to_string("accounts/template_reset_password.html", {
                    'user': associated_user,
                    'domain': get_current_site(request).domain,
                    'uid': urlsafe_base64_encode(force_bytes(associated_user.pk)),
                    'token': account_activation_token.make_token(associated_user),
                    "protocol": 'https' if request.is_secure() else 'http'
                })
                email = EmailMessage(subject, message, to=[associated_user.email])
                if email.send():
                    messages.success(request,
                        """
                        <h2>Password reset sent</h2><hr>
                        <p>
                            We've emailed you instructions for setting your password, if an account exists with the email you entered. 
                            You should receive them shortly.<br>If you don't receive an email, please make sure you've entered the address 
                            you registered with, and check your spam folder.
                        </p>
                        """
                    )
                else:
                    messages.error(request, "Problem sending reset password email, <b>SERVER PROBLEM</b>")

            return redirect('accounts:homepage')

        for key, error in list(form.errors.items()):
            if key == 'captcha' and error[0] == 'This field is required.':
                messages.error(request, "You must pass the reCAPTCHA test")
                continue

    form = PasswordResetForm()
    return render(
        request=request, 
        template_name="accounts/password_reset.html", 
        context={"form": form}
        )

def passwordResetConfirm(request, uidb64, token):
    User = get_user_model()
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except:
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        if request.method == 'POST':
            form = SetPasswordForm(user, request.POST)
            if form.is_valid():
                form.save()
                messages.success(request, "Your password has been set. You may go ahead and <b>log in </b> now.")
                return redirect('accounts:login')
            else:
                for error in list(form.errors.values()):
                    messages.error(request, error)

        form = SetPasswordForm(user)
        return render(request, 'accounts/password_reset_confirm.html', {'form': form})
    else:
        messages.error(request, "Link is expired")

    messages.error(request, 'Something went wrong, redirecting back to Homepage')
    
    return redirect("accounts:homepage")


# @login_required(login_url='login')
# def userhome(request):
#     return render(request, 'accounts/home.html')

@login_required
def logoutUser(request):
    logout(request)
    messages.info(request, "Logged out successfully!")
    return redirect("accounts:login")

mysite/accounts/templates/accounts/home.html
{% extends 'base.html' %}
{% load static %}
{% include 'accounts/messaging.html' %}

{% block content %}
    <div class="container">
        <!-- filter by category -->
        <form method="get">
            <select name="category">
                <option value="">All categories</option>
                <!-- Categories options go here -->
            </select>
            <button type="submit">Filter</button>
        </form>
        <br>
        <!-- end filter by category -->

        <div class="row" id="product-list">
            <!-- Products loop -->
            {% for product in products %}
            <div class="col-lg-3">
                <div class="product-box">
                    <div class="product-inner-box position-relative">
                        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'placeholder.jpg' %}{% endif %}" alt="{{ product.name }}">
                    </div>
                    <div class="product-info">
                        <div class="product-name">
                            <h4>{{ product.name }}</h4>
                        </div>

                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="{% url 'products:product-detail' product.id %}" class="btn btn-sm btn-outline-secondary">View</a>
                                    <i class="fa fa-shopping-cart" aria-hidden="true"></i> Add to cart
                                </a>
                            </div>
                            <small class="text-muted">{{ product.created_at }}</small>
                        </div>
                        <br>
                        <div class="product-price">
                            <p class="product-stock">In Stock: {{ product.stock }}</p>
                            <p class="product-price">Price: ${{ product.price }}</p>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            <!-- End of product loop -->
        </div>
    </div>
</div>
<script>
    const listProduct = document.querySelector('#product-list');

    async function getProducts() {
        const res = await fetch('http://127.0.0.1:8000/products/products/');
        const data = await res.json();

        data.forEach(product => {
            // Create product element
            const productElement = document.createElement('div');
            productElement.className = 'col-lg-3 product-box';

            // Create product image element
            const imageElement = document.createElement('img');
            imageElement.src = product.image ? product.image : '/static/placeholder.jpg';
            imageElement.alt = product.name;

            // Create product name element
            const nameElement = document.createElement('div');
            nameElement.className = 'product-name';
            nameElement.innerHTML = `<h4>${product.name}</h4>`;

            // Create product info element
            const infoElement = document.createElement('div');
            infoElement.className = 'product-info';

            // Create buttons for "View" and "Add to cart"
            const btnGroupElement = document.createElement('div');
            btnGroupElement.className = 'btn-group';

            // Assuming you have the product ID available in your JavaScript, you can use it like this:
            const productID = 1; // Replace this with your actual product ID

            // Construct the URL using JavaScript
            const productURL = `/products/products/${productID}/`;

            btnGroupElement.innerHTML = `
                <a href="${productURL}" class="btn btn-sm btn-outline-secondary">View</a>
                <i class="fa fa-shopping-cart" aria-hidden="true"></i> Add to cart
            `;

            // Create product stock and price elements
            const stockElement = document.createElement('p');
            stockElement.className = 'product-stock';
            stockElement.textContent = `In Stock: ${product.stock}`;

            const priceElement = document.createElement('p');
            priceElement.className = 'product-price';
            priceElement.textContent = `Price: $${product.price}`;

            // Append elements to product element
            infoElement.appendChild(nameElement);
            infoElement.appendChild(btnGroupElement);
            infoElement.appendChild(stockElement);
            infoElement.appendChild(priceElement);

            productElement.appendChild(imageElement);
            productElement.appendChild(infoElement);

            listProduct.appendChild(productElement);
        });
    }

    getProducts();
</script>
{% endblock content %}

mysite/accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
{% include 'accounts/messaging.html' %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                    {{ form|crispy }}
                </div>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Login</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need An Account? <a class="ml-2" href="{% url 'accounts:register' %}">Sign Up Now</a>
            </small><br>

        </div>
    </div>
{% endblock content%}

mysite/accounts/templates/accounts/logout.html
{% extends "base.html" %}
{% block content %}
{% include 'accounts/messaging.html' %}

    <h2>You have been logged out</h2>
    <div class="border-top pt-3"  style="min-height:65vh;">
        <small class="text-muted">
            <a href="{% url 'login' %}">Log In Again</a>
        </small>
    </div>
{% endblock content %}

mysite/accounts/templates/accounts/messaging.html
{% if messages %}
    {% for message in messages %}
        {% if message.tags == 'success' %}
            <div class="alert alert-success alert-dismissible" role="alert">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {{ message|safe|escape }}
            </div>
        {% elif message.tags == 'error' %}
            <div class="alert alert-danger alert-dismissible" role="alert">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {{ message|safe|escape }}
            </div>
        {% elif message.tags == 'info' %}
            <div class="alert alert-info alert-dismissible" role="alert">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {{ message|safe|escape }}
            </div>
        {% elif message.tags == 'warning' %}
            <div class="alert alert-warning alert-dismissible" role="alert">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {{ message|safe|escape }}
            </div>
        {% endif %}
    {% endfor %}
{% endif %}

mysite/accounts/templates/accounts/password_reset.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
	<div class="content-section">
  	 	<h2>Reset Password</h2><hr>
		<p>Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.</p>
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-outline-info" type="submit">Send email</button>
        </form>
  	</div>
{% endblock %}

mysite/accounts/templates/accounts/password_reset_confirm.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <h2>Password Reset Confirm</h2><hr>
        <p>Please enter your new password.</p>
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-outline-info" type="submit">Reset password</button>
        </form>
    </div>
{% endblock %}

mysite/accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% block content %}
  {% include 'accounts/messaging.html' %}
  <div class="container my-4">
    <div class="row">
      <div class="col-md-8">
        <h2 class="mb-4">{{ user.username }}</h2>

        <!-- Display the image if it exists -->
        {% if user.image %}
          <div class="profile-image">
            <img src="{{ user.image.url }}" alt="{{ user.username }}'s Profile Image" class="rounded-circle img-fluid">
          </div>
        {% endif %}

        <form method="post" action="{% url 'accounts:profile' %}" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="form-group">
            <label for="first_name">First Name</label>
            <input type="text" name="first_name" id="first_name" class="form-control" value="{{ user.first_name }}" required>
          </div>
          <div class="form-group">
            <label for="last_name">Last Name</label>
            <input type="text" name="last_name" id="last_name" class="form-control" value="{{ user.last_name }}" required>
          </div>
          <div class="form-group">
            <label for="image">Profile Image</label>
            <input type="file" name="image" id="image" class="form-control-file">
          </div>
          <div class="form-group">
            <label for="email">Email</label>
            <input type="email" name="email" id="email" class="form-control" value="{{ user.email }}" required>
          </div>
          <div class="form-group">
            <label for="phone_number">Phone Number</label>
            <input type="tel" name="phone_number" id="phone_number" class="form-control" value="{{ user.phone_number }}" required>
          </div>
          <div class="form-group">
            <label for="address">Address</label>
            <textarea name="address" id="address" class="form-control" required>{{ user.address }}</textarea>
          </div>
          <button type="submit" class="btn btn-primary">Update Profile</button>
        </form>
      </div>
    </div>
  </div>
  <style>
    .profile-image {
      width: 150px; /* Adjust the size as needed */
      height: 150px; /* Adjust the size as needed */
      overflow: hidden;
      border-radius: 50%;
      margin: 0 auto;
      border: 2px solid #007BFF; /* Add a border */
    }

    .profile-image img {
      width: 100%;
      height: 100%;
      object-fit: cover;
    }
  </style>
{% endblock %}

mysite/accounts/templates/accounts/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
{% include 'accounts/messaging.html' %}

    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                {{ form|crispy }}
            </fieldset>

            By registering, you accept the Terms of Service and Privacy Notice

            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already Have An Account? <a class="ml-2" href="{% url 'accounts:login' %}">Sign In</a>
            </small>
        </div>
    </div>

{% endblock content%}

mysite/accounts/templates/accounts/template_activate_account.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

{{ protocol }}://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}
{% endautoescape %}

mysite/accounts/templates/accounts/template_reset_password.html
{% autoescape off %}
Hello {{ user.username }},

We received a request to reset the password for your account for this email address. To initiate the password reset process for your account, click the link below.

{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

This link can only be used once. If you need to reset your password again, please visit {{ protocol }}://{{domain}} and request another reset.

If you did not make this request, you can simply ignore this email.

Sincerely,
PyLessons

{% endautoescape %}